// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBosm04uU23ot8NO97StCsSZDvFL_iNIKI',
    appId: '1:797655594738:web:dbc3f944f236622b1dc26b',
    messagingSenderId: '797655594738',
    projectId: 'illdoit-app',
    authDomain: 'illdoit-app.firebaseapp.com',
    storageBucket: 'illdoit-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6TjMZ9Xya8frm90kpj9wxZvTVHe34Wo',
    appId: '1:797655594738:android:841fd143af5e0a8b1dc26b',
    messagingSenderId: '797655594738',
    projectId: 'illdoit-app',
    storageBucket: 'illdoit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP24u6JcaoA6DKCRis8SWYBKkjADlywBY',
    appId: '1:797655594738:ios:16f682684b7601381dc26b',
    messagingSenderId: '797655594738',
    projectId: 'illdoit-app',
    storageBucket: 'illdoit-app.firebasestorage.app',
    iosBundleId: 'com.example.illDoIt',
  );

}